name: Build and push docker image

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  build-and-deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Get the tag name
#         run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
#       - name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: rparias/razors:${{ env.TAG }},rparias/razors:latest
#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
